### ISSUE TITLE
What does mrubyvisor can do?

### ISSUE THREAD

**Issue by ccmywish** [tailix/mrubyvisor#1]
Hello @kotovalexarian, I found this project in `gitter.im`. 

I have some experience with mruby, and read some code, but never try to write a mruby plugin or something. I'm quite interested in it because I'm always finding how people use mruby.

However, I have little knowledge in OS development. So, I don't know what this project can do. Could you please explain something more about this project? Or could you provide some links so I can track to get to know it? 

Thank you!

**Comment by kotovalexarian** [comment]
Hello! I'm glad that you are interested.

This application can run Ruby code in freestanding environment, without any operating system kernel. You can run it on real hardware, but this is not useful for development so I run it in QEMU virtual machine. This is what happens when you run `make runc` command.

For now it is not very impressive because there is no Ruby API to access the hardware. Usually you have a standard library that gives you access to stdio, files, network, etc. These things don't exist in the freestanding environment. If you want to access disks or network cards, you have to write a driver. However, Ruby can't access memory or other hardware by default. I want to write an API to make it possible.

The purpose of this project is to make freestanding environment more accessible to humans by bringing there an interactive shell with a very dynamic language.
